# Generated by Django 5.2.15 on 2026-06-13 17:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready')], default='draft', max_length=16)),
                ('completion', models.PositiveSmallIntegerField(default=0)),
                ('courseDescription', models.TextField(blank=True, default='')),
                ('courseGoal', models.TextField(blank=True, default='')),
                ('teachingPhilosophy', models.TextField(blank=True, default='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabuses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignatureBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparedByName', models.CharField(blank=True, default='', max_length=255)),
                ('preparedByPosition', models.CharField(blank=True, default='', max_length=255)),
                ('preparedByDate', models.CharField(blank=True, default='', max_length=64)),
                ('signatureImage', models.TextField(blank=True, default='')),
                ('stampImage', models.TextField(blank=True, default='')),
                ('syllabus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='syllabuses.syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='LiteratureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('required', 'Required'), ('additional', 'Additional'), ('internet', 'Internet')], max_length=32)),
                ('order', models.PositiveIntegerField(default=1)),
                ('text', models.TextField(blank=True, default='')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literatureItems', to='syllabuses.syllabus')),
            ],
            options={
                'ordering': ['type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LearningOutcomeRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('courseLearningOutcome', models.TextField(blank=True, default='')),
                ('programLearningOutcome', models.TextField(blank=True, default='')),
                ('code', models.CharField(blank=True, default='', max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learningOutcomes', to='syllabuses.syllabus')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CoursePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masteringDiscipline', models.TextField(blank=True, default='')),
                ('allowed', models.TextField(blank=True, default='')),
                ('notAllowed', models.TextField(blank=True, default='')),
                ('examEthics', models.TextField(blank=True, default='')),
                ('informationCommunication', models.TextField(blank=True, default='')),
                ('syllabus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coursePolicy', to='syllabuses.syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='ClassScheduleRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('week', models.CharField(blank=True, default='', max_length=64)),
                ('topic', models.TextField(blank=True, default='')),
                ('format', models.TextField(blank=True, default='')),
                ('task', models.TextField(blank=True, default='')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classSchedule', to='syllabuses.syllabus')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('topicModule', models.TextField(blank=True, default='')),
                ('maxPercent', models.CharField(blank=True, default='', max_length=32)),
                ('maxWeight', models.CharField(blank=True, default='', max_length=32)),
                ('finalPoints', models.CharField(blank=True, default='', max_length=32)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessmentSystem', to='syllabuses.syllabus')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusTitleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeAndName', models.CharField(blank=True, default='', max_length=255)),
                ('credits', models.CharField(blank=True, default='', max_length=32)),
                ('totalHours', models.CharField(blank=True, default='', max_length=32)),
                ('classroomHours', models.CharField(blank=True, default='', max_length=32)),
                ('independentWorkHours', models.CharField(blank=True, default='', max_length=32)),
                ('prerequisites', models.TextField(blank=True, default='')),
                ('levelOfTraining', models.CharField(blank=True, default='', max_length=255)),
                ('semester', models.CharField(blank=True, default='', max_length=255)),
                ('educationalProgram', models.CharField(blank=True, default='', max_length=255)),
                ('languageOfEducation', models.CharField(blank=True, default='', max_length=64)),
                ('proficiencyLevel', models.CharField(blank=True, default='', max_length=255)),
                ('formatOfTraining', models.CharField(blank=True, default='', max_length=255)),
                ('instructorName', models.CharField(blank=True, default='', max_length=255)),
                ('instructorDegree', models.CharField(blank=True, default='', max_length=255)),
                ('instructorEmail', models.EmailField(blank=True, default='', max_length=254)),
                ('instructorContacts', models.TextField(blank=True, default='')),
                ('timeAndPlace', models.TextField(blank=True, default='')),
                ('syllabus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='titleInfo', to='syllabuses.syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='ThematicPlanRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('week', models.CharField(blank=True, default='', max_length=64)),
                ('topicModule', models.TextField(blank=True, default='')),
                ('courseOutcome', models.TextField(blank=True, default='')),
                ('questions', models.TextField(blank=True, default='')),
                ('tasks', models.TextField(blank=True, default='')),
                ('literature', models.TextField(blank=True, default='')),
                ('gradeStructure', models.TextField(blank=True, default='')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thematicPlan', to='syllabuses.syllabus')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
